title: Word Search Generator
description: Simple JavaScript word search generator

compress_html:
    clippings: all

sass:
    sass_dir: assets/style/
    style: :compressed

github: http://github.com/roryclaasen/word-search-generator/tree/game
