name: Dev

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 16.16.0
  PNPM_VERSION: 7.9.0

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: |
            **/package-lock.json
            **/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint Code
        run: pnpm lint

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: |
            **/package-lock.json
            **/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint Code
        run: pnpm build
